name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Where Am I?
        run: |
          ls -a

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Coverage
        run: |
          pip install pytest pytest-cov
          pytest Abgabe6/Hangman.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html